[build]
  command = "npm run build"
  publish = "dist"

# Single Page App history fallback so client routes work on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Inject security headers. Adjust VITE_API_BASE / API domain in connect-src if using cross-origin.
[[headers]]
  for = "/*"
    [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
  # Updated connect-src with actual Railway API host
  Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data:; connect-src 'self' https://enthusiastic-quietude-production-b41f.up.railway.app; object-src 'none'; base-uri 'self'; frame-ancestors 'none'"
